# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI
on: 
 push:
  branches: ["main"]
 pull_request:
  branches: ["main"]
 
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2.4.2
   - name: Setup JDK
     uses: actions/setup-java@v3.4.1
     with:
        java-version: 11
   - name: Build with Gradle
     run: ./gradlew build
   - name: Upload APK
     uses: actions/upload-artifact@v3.1.0
     with:
        name: app
        path: app/build/apk/debug/app-debug.apk
